// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Carreiras-VagasAbertas', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Carreiras-VagasAbertas', async function() {
    await driver.get("https://qa.medcloud.link/")
    await driver.findElement(By.linkText("Carreiras")).click()
    await driver.findElement(By.css(".mt-8 > .text-secondary")).click()
    assert(await driver.findElement(By.css(".px-32 > .text-left")).getText() == "Confira as vagas abertas")
  })
})
