// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Carreiras-FormularioCandidatura', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Carreiras-FormularioCandidatura', async function() {
    await driver.get("https://qa.medcloud.link/")
    await driver.findElement(By.linkText("Carreiras")).click()
    await driver.findElement(By.css(".mt-8 > .text-secondary")).click()
    await driver.executeScript("window.scrollTo(0,4153)")
    await driver.findElement(By.css(".w-1\\/3:nth-child(2) .absolute")).click()
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys("João da ")
    await driver.findElement(By.id("name")).sendKeys(Key.ENTER)
    await driver.findElement(By.id("lastName")).sendKeys("Cainan")
    await driver.findElement(By.id("lastName")).sendKeys(Key.ENTER)
    await driver.findElement(By.id("email")).sendKeys("cainan")
    await driver.findElement(By.id("email")).sendKeys(Key.ENTER)
    await driver.findElement(By.id("email")).sendKeys("cainan@")
    await driver.findElement(By.id("email")).sendKeys(Key.ENTER)
    await driver.findElement(By.id("email")).sendKeys("cainan@cainan.com")
    await driver.findElement(By.id("email")).sendKeys(Key.ENTER)
    await driver.findElement(By.id("phone")).sendKeys("2321234132")
    await driver.findElement(By.id("phone")).sendKeys(Key.ENTER)
    await driver.findElement(By.id("message")).sendKeys("teste\\n")
    await driver.findElement(By.id("fileName")).click()
    // É possível enviar o formulário com um arquivo que não seja pdf, o que não deveria, invalidando o teste
    await driver.findElement(By.id("curriculum")).sendKeys("C:\\fakepath\\clock.rmpf")
    await driver.findElement(By.css(".text-xs")).click()
    assert(await driver.findElement(By.css(".sm\\3Ainline")).getText() == "Sua candidatura para a vaga de Analista de Suporte foi efetuada com sucesso!")
  })
})
