// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Contato-FormularioContato', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Contato-FormularioContato', async function() {
    await driver.get("https://qa.medcloud.link/")
    await driver.findElement(By.css(".flex > .flex-col #name")).click()
    await driver.findElement(By.css(".flex > .flex-col #name")).sendKeys("Cainan")
    await driver.findElement(By.css(".xxl\\3Ah-12")).click()
    assert(await driver.findElement(By.css(".sm\\3Ainline")).getText() == "Erro ao enviar mensagem.")
    await driver.findElement(By.css(".flex > .flex-col #email")).click()
    await driver.findElement(By.css(".flex > .flex-col #email")).sendKeys("cainan")
    await driver.findElement(By.css(".xxl\\3Ah-12")).click()
    await driver.findElement(By.css(".flex > .flex-col #email")).sendKeys("cainan@")
    await driver.findElement(By.css(".xxl\\3Ah-12")).click()
    await driver.findElement(By.css(".flex > .flex-col #email")).sendKeys("cainan@cainan.com")
    await driver.findElement(By.css(".xxl\\3Ah-12")).click()
    assert(await driver.findElement(By.css(".sm\\3Ainline")).getText() == "Erro ao enviar mensagem.")
    await driver.findElement(By.css(".flex > .flex-col #phone")).click()
    // OBS: Campo deixa digitar letras, ao invés de somente números, invalidando o teste
    await driver.findElement(By.css(".flex > .flex-col #phone")).sendKeys("4299999999")
    await driver.findElement(By.id("message")).click()
    await driver.findElement(By.id("message")).sendKeys("mensagem")
    await driver.findElement(By.css(".xxl\\3Ah-12")).click()
    assert(await driver.findElement(By.css(".sm\\3Ainline")).getText() == "Mensagem enviada com sucesso.")
  })
})
