// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Footer-LinkedIn', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Footer-LinkedIn', async function() {
    await driver.get("https://qa.medcloud.link/")
    {
      const attribute = await driver.findElement(By.xpath("//*[@id=\"__next\"]/section[7]/section/div[1]/div[1]/div/a[6]")).getAttribute("href")
      vars["x"] = attribute
    }
    assert(vars["x"].toString() == "https://www.linkedin.com/company/medcloud/")
    await driver.findElement(By.css("a:nth-child(6)")).click()
    await driver.sleep(3000)
    assert(await driver.findElement(By.css(".top-card-layout__title")).getText() == "Medcloud")
  })
})
