// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Footer-Sobre', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Footer-Sobre', async function() {
    await driver.get("https://qa.medcloud.link/")
    {
      const attribute = await driver.findElement(By.xpath("//*[@id=\"__next\"]/section[7]/section/div[1]/div[2]/div[2]/ul/li[1]/a")).getAttribute("href")
      vars["x"] = attribute
    }
    assert(vars["x"].toString() == "about.html")
    await driver.findElement(By.linkText("Sobre")).click()
    await driver.sleep(2000)
    assert(await driver.findElement(By.css(".leading-10:nth-child(1)")).getText() == "Sobre nós")
  })
})
