// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Footer-Twitter', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Footer-Twitter', async function() {
    await driver.get("https://qa.medcloud.link/")
    {
      const attribute = await driver.findElement(By.xpath("//*[@id=\"__next\"]/section[7]/section/div[1]/div[1]/div/a[4]")).getAttribute("href")
      vars["x"] = attribute
    }
    assert(vars["x"].toString() == "https://twitter.com/medcloudbr")
    await driver.findElement(By.css("a:nth-child(4)")).click()
    await driver.sleep(4000)
    assert(await driver.findElement(By.css(".x1ms8i2q")).getText() == "medcloudbr")
  })
})
