// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Footer-Spotify', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Footer-Spotify', async function() {
    await driver.get("https://qa.medcloud.link/")
    {
      const attribute = await driver.findElement(By.xpath("//*[@id=\"__next\"]/section[7]/section/div[1]/div[1]/div/a[1]")).getAttribute("href")
      vars["x"] = attribute
    }
    assert(vars["x"].toString() == "https://open.spotify.com/show/4IK3IeDsKHbflXLQ6oy20W")
    await driver.findElement(By.css(".space-x-6 > a:nth-child(1)")).click()
    await driver.sleep(3000)
    assert(await driver.findElement(By.css(".hulXhb:nth-child(3)")).getText() == "Momento Saúde Digital")
  })
})
