// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Footer-TraducaoIngles', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Footer-TraducaoIngles', async function() {
    await driver.get("https://qa.medcloud.link/")
    await driver.findElement(By.css(".float-right:nth-child(3)")).click()
    await driver.executeScript("window.scrollBy(0, -700);")
    await driver.sleep(1000)
    assert(await driver.findElement(By.css(".sm\\3Atext-left > p:nth-child(1)")).getText() == "Leave a message, question or comment below.")
  })
})
