// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Footer-TermosUso', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Footer-TermosUso', async function() {
    await driver.get("https://qa.medcloud.link/")
    {
      const attribute = await driver.findElement(By.xpath("//*[@id=\"__next\"]/section[7]/section/div[1]/div[2]/div[2]/ul/li[4]/a")).getAttribute("href")
      vars["x"] = attribute
    }
    assert(vars["x"].toString() == "/pdfs/Medcloud-Terms-Use.pdf")
    await driver.findElement(By.linkText("Termos de uso")).click()
  })
})
