// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Header-Carreiras-VoltarTelaInicial', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Header-Carreiras-VoltarTelaInicial', async function() {
    await driver.get("https://qa.medcloud.link/")
    await driver.findElement(By.linkText("Carreiras")).click()
    await driver.findElement(By.linkText("Voltar ao site")).click()
    assert(await driver.findElement(By.css(".sm\\3Atext-mob11xl")).getText() == "Seus exames\\\\nna nuvem")
  })
})
