// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Header-TestarGratis', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Header-TestarGratis', async function() {
    await driver.get("https://qa.medcloud.link/")
    await driver.findElement(By.css(".h-full > .text-white")).click()
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys(Key.ENTER)
    await driver.findElement(By.id("name")).sendKeys("Cainan Rhoden")
    await driver.findElement(By.id("name")).sendKeys(Key.ENTER)
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("cainan")
    await driver.findElement(By.id("email")).sendKeys(Key.ENTER)
    await driver.findElement(By.id("email")).sendKeys("cainan@")
    await driver.findElement(By.id("email")).sendKeys(Key.ENTER)
    await driver.findElement(By.id("email")).sendKeys("cainan@cainan.com")
    await driver.findElement(By.id("email")).sendKeys(Key.ENTER)
    await driver.findElement(By.id("phone")).sendKeys("246778997")
    await driver.findElement(By.id("pos")).click()
    {
      const dropdown = await driver.findElement(By.id("pos"))
      await dropdown.findElement(By.xpath("//option[. = 'Gestor de T.I']")).click()
    }
    await driver.findElement(By.css(".mt-8 > .xxl\\3Atext-base")).click()
    assert(await driver.findElement(By.css(".sm\\3Ainline")).getText() == "Trial solicitado com sucesso!")
  })
})
