// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Sobre-ConfiraVagas', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Sobre-ConfiraVagas', async function() {
    await driver.get("https://qa.medcloud.link/")
    await driver.findElement(By.linkText("Sobre")).click()
    await driver.findElement(By.css(".sm\\3Amy-0")).click()
    await driver.executeScript("window.scrollBy(0, 200);")
    assert(await driver.findElement(By.css(".sm\\3Atext-left")).getText() == "Faça parte do Time Medcloud!")
  })
})
