// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Sobre-EntreEmContato', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Sobre-EntreEmContato', async function() {
    await driver.get("https://qa.medcloud.link/")
    await driver.findElement(By.linkText("Sobre")).click()
    {
      const attribute = await driver.findElement(By.xpath("//*[@id=\"Partner\"]/div/button/a")).getAttribute("href")
      vars["x"] = attribute
    }
    assert(vars["x"].toString() == "mailto:mpp@medcloud.com.br")
    await driver.findElement(By.linkText("Entre em contato")).click()
  })
})
